### ISSUE TITLE
Can't zip an individual file

### ISSUE THREAD

**Issue by swelshh** [miyako/wak-zip#1]
Hi Miyako,

Great idea for a module, thank you for making it available.

I'm having trouble zipping individual files.  I'm trying this on OS X 10.9.5 with both Wak 9.175128 and Wak 10.176011.

I can zip a folder and everything works great.  But whenever I try to zip an individual file, I get a test.zip file that is always 22 bytes.  Trying to unzip by double clicking always creates a test.zip.cpgz with 128 bytes.

Can I zip individual files with this module, or do I have to put a file inside a folder, then zip the folder?

Thanks!
Welsh

**Comment by miyako** [comment]
Thank's for testing, it should be OK now!

**Comment by swelshh** [comment]
Awesome, works great, Thank you!
