### ISSUE TITLE
Problems zipping a file on Windows Server 2012

### ISSUE THREAD

**Issue by swelshh** [miyako/wak-zip#2]
Hello,

When I try to zip an individual file on Windows Server 2012 (64-bit), I always get a zip file with 0KB.

**Comment by swelshh** [comment]
Hey there, just checking in.  I'm still having this issue with the most recent build.  Do you think there will be a version that works for Win Server 2012?

**Comment by miyako** [comment]
you know, what I "think" is irrelevant.
it would help more if you actually described what the issue is.

**Comment by miyako** [comment]
more specifically, what does the return value from zip.zip() look like?

**Comment by miyako** [comment]
actually, it seems like system workers systematically fail on windows.
do you have any code (from the documentation, even) that successfully runs a system worker?

**Comment by swelshh** [comment]
Hello, system workers are broken in Wak10 on windows, bugs are registered as:
WAK0090944
WAK0090934

They do seem to work well in Wak9 though.

And sorry I wasn't more specific.  I only have one Win 2012 server and unfortunately it is also running my production Wakanda server.  I will be doing some maintenance this weekend and will get more details about the issue.

**Comment by miyako** [comment]
So to be clear, does it NOT work on Windows 2012, even if you use WAK9?

**Comment by swelshh** [comment]
So sorry.  Tested again using Wak9 on Windows Server 2012 and the newest version of your module is working.  Sorry to waste your time, and thanks again for building a great module.
