### ISSUE TITLE
Can't run on Windows 7

### ISSUE THREAD

**Issue by swelshh** [miyako/wak-zip#3]
Hello,

Tried running this on a Windows 7 (64-bit) machine, but doesn't seem to work...

![screen shot 2015-01-13 at 1 59 41 pm](https://cloud.githubusercontent.com/assets/1295707/5728150/bc1f5e6c-9b2d-11e4-9393-aa2875545396.png)
![screen shot 2015-01-13 at 2 03 03 pm](https://cloud.githubusercontent.com/assets/1295707/5728149/bc1e3cd0-9b2d-11e4-91f6-adfa59a781d4.png)

**Comment by miyako** [comment]
Thanks for the feedback!

looks like boost doesn't like dynamic linkage on Windows,
changed to static linking,
could you try again?

[cid:imageb87ebd.JPG@8cdbca49.4089df50]
宮古 啓介
セールス・エンジニア
Tel:    03-6427-8441
E-mail: Keisuke.Miyako@4d.com
Web:    www.4D.com/JP

株式会社フォーディー・ジャパン
〒150-0043
東京都渋谷区道玄坂1-10-2 渋谷THビル6F
Tel:    03-6427-8441
Fax:    03-6427-8449

**Comment by swelshh** [comment]
For sure! this is a really great module.

I just tried the new version and I'm seeing the same problem.  Same as the screenshot in my first post.  Also, I forgot to include this error message that comes up when I run the zip.zip command...

![screen shot 2015-01-14 at 10 01 47 am](https://cloud.githubusercontent.com/assets/1295707/5742002/9d411c86-9bd4-11e4-99f4-fb2aab872d5e.png)

**Comment by miyako** [comment]
OK, well I suppose I must re-write without boost then.
Please allow me to work on it for a couple of hours...

[cid:imagea992d3.JPG@e50b3e4f.4aab9f34]
宮古 啓介
セールス・エンジニア
Tel:    03-6427-8441
E-mail: Keisuke.Miyako@4d.com
Web:    www.4D.com/JP

株式会社フォーディー・ジャパン
〒150-0043
東京都渋谷区道玄坂1-10-2 渋谷THビル6F
Tel:    03-6427-8441
Fax:    03-6427-8449

**Comment by miyako** [comment]
zip should be OK now.
next is unzip...

[cid:imagec06042.JPG@fff79e35.449794c0]
宮古 啓介
セールス・エンジニア
Tel:    03-6427-8441
E-mail: Keisuke.Miyako@4d.com
Web:    www.4D.com/JP

株式会社フォーディー・ジャパン
〒150-0043
東京都渋谷区道玄坂1-10-2 渋谷THビル6F
Tel:    03-6427-8441
Fax:    03-6427-8449

**Comment by swelshh** [comment]
Fixed!  thank you.
